<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\Patient;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            // Patients for Lagos General Hospital (ABCD)
            [
                'clinic_id' => 'ABCD',
                'patient_id' => 'ABCD-2025-0001',
                'first_name' => 'Chukwuma',
                'last_name' => 'Okafor',
                'middle_name' => 'Emmanuel',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'photo_path' => null,
                'phone' => '+234-803-111-2222',
                'email' => 'chukwuma.okafor@email.com',
                'address' => '45 Broad Street',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Ikeja',
                'postal_code' => '100001',
                'test_date' => '2025-01-10',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'positive',
                'viral_load' => 15000,
                'alt_level' => 85,
                'ast_level' => 72,
                'platelet_count' => 180,
                'lab_notes' => 'High viral load detected. Recommend treatment initiation.',
                'diagnosis_type' => 'chronic',
                'treatment_status' => 'on_treatment',
                'vaccination_status' => 'not_vaccinated',
                'prescribed_medication' => 'Tenofovir 300mg once daily',
                'next_appointment' => '2025-02-10',
                'doctor_name' => 'Dr. Adebayo Johnson',
                'treatment_notes' => 'Patient started on antiviral therapy. Monitor liver function monthly.',
            ],
            [
                'clinic_id' => 'ABCD',
                'patient_id' => 'ABCD-2025-0002',
                'first_name' => 'Amina',
                'last_name' => 'Bello',
                'middle_name' => 'Fatima',
                'date_of_birth' => '1992-07-22',
                'gender' => 'female',
                'photo_path' => null,
                'phone' => '+234-805-222-3333',
                'email' => 'amina.bello@email.com',
                'address' => '12 Allen Avenue',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Ikeja',
                'postal_code' => '100001',
                'test_date' => '2025-01-12',
                'hbsag' => 'negative',
                'anti_hbs' => 'positive',
                'hbeag' => null,
                'viral_load' => null,
                'alt_level' => 28,
                'ast_level' => 32,
                'platelet_count' => 250,
                'lab_notes' => 'Immunity confirmed. No treatment needed.',
                'diagnosis_type' => 'resolved',
                'treatment_status' => 'monitoring',
                'vaccination_status' => 'fully_vaccinated',
                'prescribed_medication' => null,
                'next_appointment' => '2025-07-12',
                'doctor_name' => 'Dr. Adebayo Johnson',
                'treatment_notes' => 'Annual checkup recommended.',
            ],
            [
                'clinic_id' => 'ABCD',
                'patient_id' => 'ABCD-2025-0003',
                'first_name' => 'Oluwaseun',
                'last_name' => 'Adeyemi',
                'middle_name' => 'Grace',
                'date_of_birth' => '1978-11-05',
                'gender' => 'female',
                'photo_path' => null,
                'phone' => '+234-807-333-4444',
                'email' => null,
                'address' => '89 Victoria Island Road',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Lagos Island',
                'postal_code' => '101001',
                'test_date' => '2025-01-08',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'negative',
                'viral_load' => 500,
                'alt_level' => 35,
                'ast_level' => 38,
                'platelet_count' => 220,
                'lab_notes' => 'Inactive carrier state. Low viral load.',
                'diagnosis_type' => 'carrier',
                'treatment_status' => 'monitoring',
                'vaccination_status' => 'not_vaccinated',
                'prescribed_medication' => null,
                'next_appointment' => '2025-04-08',
                'doctor_name' => 'Dr. Adebayo Johnson',
                'treatment_notes' => 'Monitor every 3 months. Treatment may be needed if viral load increases.',
            ],

            // Patients for Abuja Medical Center (EFGH)
            [
                'clinic_id' => 'EFGH',
                'patient_id' => 'EFGH-2025-0001',
                'first_name' => 'Mohammed',
                'last_name' => 'Ibrahim',
                'middle_name' => 'Yusuf',
                'date_of_birth' => '1988-05-18',
                'gender' => 'male',
                'photo_path' => null,
                'phone' => '+234-809-444-5555',
                'email' => 'mohammed.ibrahim@email.com',
                'address' => '23 Gwarimpa Estate',
                'country' => 'Nigeria',
                'state' => 'Abuja',
                'city' => 'Garki',
                'postal_code' => '900001',
                'test_date' => '2025-01-15',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'positive',
                'viral_load' => 25000,
                'alt_level' => 120,
                'ast_level' => 95,
                'platelet_count' => 165,
                'lab_notes' => 'Elevated liver enzymes. Active replication.',
                'diagnosis_type' => 'chronic',
                'treatment_status' => 'not_started',
                'vaccination_status' => 'not_vaccinated',
                'prescribed_medication' => 'Entecavir 0.5mg once daily - to be started',
                'next_appointment' => '2025-01-25',
                'doctor_name' => 'Dr. Ngozi Okonkwo',
                'treatment_notes' => 'Counseling on treatment adherence scheduled. Treatment to begin next visit.',
            ],
            [
                'clinic_id' => 'EFGH',
                'patient_id' => 'EFGH-2025-0002',
                'first_name' => 'Elizabeth',
                'last_name' => 'Obi',
                'middle_name' => 'Chioma',
                'date_of_birth' => '1995-09-30',
                'gender' => 'female',
                'photo_path' => null,
                'phone' => '+234-810-555-6666',
                'email' => 'elizabeth.obi@email.com',
                'address' => '67 Asokoro District',
                'country' => 'Nigeria',
                'state' => 'Abuja',
                'city' => 'Asokoro',
                'postal_code' => '900231',
                'test_date' => '2025-01-14',
                'hbsag' => 'pending',
                'anti_hbs' => 'pending',
                'hbeag' => null,
                'viral_load' => null,
                'alt_level' => null,
                'ast_level' => null,
                'platelet_count' => null,
                'lab_notes' => 'Samples sent to laboratory. Results pending.',
                'diagnosis_type' => 'acute',
                'treatment_status' => 'monitoring',
                'vaccination_status' => 'partially_vaccinated',
                'prescribed_medication' => null,
                'next_appointment' => '2025-01-21',
                'doctor_name' => 'Dr. Ngozi Okonkwo',
                'treatment_notes' => 'Follow-up scheduled for test results review.',
            ],

            // Patients for Kano Infectious Disease Clinic (IJKL)
            [
                'clinic_id' => 'IJKL',
                'patient_id' => 'IJKL-2025-0001',
                'first_name' => 'Abubakar',
                'last_name' => 'Sani',
                'middle_name' => 'Ahmad',
                'date_of_birth' => '1980-12-12',
                'gender' => 'male',
                'photo_path' => null,
                'phone' => '+234-812-666-7777',
                'email' => null,
                'address' => '156 Bompai Road',
                'country' => 'Nigeria',
                'state' => 'Kano',
                'city' => 'Kano Municipal',
                'postal_code' => '700001',
                'test_date' => '2025-01-05',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'negative',
                'viral_load' => 8000,
                'alt_level' => 65,
                'ast_level' => 58,
                'platelet_count' => 195,
                'lab_notes' => 'Moderate viral load. Liver enzymes mildly elevated.',
                'diagnosis_type' => 'chronic',
                'treatment_status' => 'on_treatment',
                'vaccination_status' => 'not_vaccinated',
                'prescribed_medication' => 'Tenofovir 300mg once daily',
                'next_appointment' => '2025-02-05',
                'doctor_name' => 'Dr. Ibrahim Musa',
                'treatment_notes' => 'Patient responding well to treatment. Continue current regimen.',
            ],

            // Patients for Accra Health Clinic (MNOP)
            [
                'clinic_id' => 'MNOP',
                'patient_id' => 'MNOP-2025-0001',
                'first_name' => 'Kwame',
                'last_name' => 'Asante',
                'middle_name' => 'Kofi',
                'date_of_birth' => '1990-04-08',
                'gender' => 'male',
                'photo_path' => null,
                'phone' => '+233-24-777-8888',
                'email' => 'kwame.asante@email.com',
                'address' => '45 Ring Road East',
                'country' => 'Ghana',
                'state' => 'Greater Accra',
                'city' => 'Accra',
                'postal_code' => 'GA-123-4567',
                'test_date' => '2025-01-11',
                'hbsag' => 'negative',
                'anti_hbs' => 'positive',
                'hbeag' => null,
                'viral_load' => null,
                'alt_level' => 30,
                'ast_level' => 28,
                'platelet_count' => 240,
                'lab_notes' => 'Post-vaccination immunity confirmed.',
                'diagnosis_type' => 'resolved',
                'treatment_status' => 'completed',
                'vaccination_status' => 'fully_vaccinated',
                'prescribed_medication' => null,
                'next_appointment' => null,
                'doctor_name' => 'Dr. Kwame Mensah',
                'treatment_notes' => 'No further follow-up needed unless symptoms develop.',
            ],

            // Patients for Nairobi Central Clinic (QRST)
            [
                'clinic_id' => 'QRST',
                'patient_id' => 'QRST-2025-0001',
                'first_name' => 'Grace',
                'last_name' => 'Wanjiku',
                'middle_name' => 'Mumbi',
                'date_of_birth' => '1987-06-25',
                'gender' => 'female',
                'photo_path' => null,
                'phone' => '+254-722-888-9999',
                'email' => 'grace.wanjiku@email.com',
                'address' => '78 Ngong Road',
                'country' => 'Kenya',
                'state' => 'Nairobi',
                'city' => 'Nairobi',
                'postal_code' => '00100',
                'test_date' => '2025-01-13',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'positive',
                'viral_load' => 18000,
                'alt_level' => 95,
                'ast_level' => 88,
                'platelet_count' => 175,
                'lab_notes' => 'Active viral replication. Treatment recommended.',
                'diagnosis_type' => 'chronic',
                'treatment_status' => 'on_treatment',
                'vaccination_status' => 'not_vaccinated',
                'prescribed_medication' => 'Entecavir 0.5mg once daily',
                'next_appointment' => '2025-02-13',
                'doctor_name' => 'Dr. James Kamau',
                'treatment_notes' => 'Patient educated on treatment importance. Good adherence expected.',
            ],
            [
                'clinic_id' => 'QRST',
                'patient_id' => 'QRST-2025-0002',
                'first_name' => 'David',
                'last_name' => 'Omondi',
                'middle_name' => 'Otieno',
                'date_of_birth' => '1993-02-14',
                'gender' => 'male',
                'photo_path' => null,
                'phone' => '+254-733-999-0000',
                'email' => 'david.omondi@email.com',
                'address' => '34 Moi Avenue',
                'country' => 'Kenya',
                'state' => 'Nairobi',
                'city' => 'Nairobi',
                'postal_code' => '00200',
                'test_date' => '2025-01-09',
                'hbsag' => 'positive',
                'anti_hbs' => 'negative',
                'hbeag' => 'negative',
                'viral_load' => 1200,
                'alt_level' => 42,
                'ast_level' => 38,
                'platelet_count' => 210,
                'lab_notes' => 'Very low viral load. Inactive carrier.',
                'diagnosis_type' => 'carrier',
                'treatment_status' => 'monitoring',
                'vaccination_status' => 'partially_vaccinated',
                'prescribed_medication' => null,
                'next_appointment' => '2025-04-09',
                'doctor_name' => 'Dr. James Kamau',
                'treatment_notes' => 'Monitor quarterly. No treatment required at this time.',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }

        $this->command->info('Patients seeded successfully!');
    }
}