<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HospitalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hospitals = [
            [
                'hospital_name' => 'John Max Well Hospital',
                'hospital_type' => 'general',
                'reg_no' => 'ng/2026/01234',
                'lic_issue_dt' => '2024-01-15',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. John Maxwell',
                'ownership' => 'private',
                'beds' => 150,
                'email' => 'info@johnmaxwell.hospital',
                'contact_no' => '+234-801-234-5678',
                'address' => '45 Victoria Island Road, Lagos',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Lagos',
                'zipcode' => '101001',
                'latitude' => 6.4281,
                'longitude' => 3.4219,
                'logo_path' => 'logos/john_max_well_hospital.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Goodness Clinic',
                'hospital_type' => 'specialty',
                'reg_no' => 'usa/2026/01237',
                'lic_issue_dt' => '2023-06-20',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Sarah Goodness',
                'ownership' => 'private',
                'beds' => 80,
                'email' => 'contact@goodnessclinic.com',
                'contact_no' => '+1-555-789-0123',
                'address' => '1234 Medical Center Drive, Los Angeles, CA',
                'country' => 'USA',
                'state' => 'California',
                'city' => 'Los Angeles',
                'zipcode' => '90001',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'logo_path' => 'logos/goodness_clinic.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Royal Care Medical Center',
                'hospital_type' => 'teaching',
                'reg_no' => 'ng/2026/01235',
                'lic_issue_dt' => '2022-03-10',
                'accred_status' => 'accredited',
                'med_dir' => 'Prof. Adewale Okonkwo',
                'ownership' => 'government',
                'beds' => 300,
                'email' => 'admin@royalcare.ng',
                'contact_no' => '+234-802-345-6789',
                'address' => '12 Broad Street, Ikoyi, Lagos',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Lagos',
                'zipcode' => '101004',
                'latitude' => 6.4531,
                'longitude' => 3.4239,
                'logo_path' => 'logos/royal_care_medical_center.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Sunrise Health Facility',
                'hospital_type' => 'community',
                'reg_no' => 'ng/2026/01236',
                'lic_issue_dt' => '2024-08-05',
                'accred_status' => 'pending',
                'med_dir' => 'Dr. Chioma Nwosu',
                'ownership' => 'charitable',
                'beds' => 50,
                'email' => 'hello@sunrisehealth.org',
                'contact_no' => '+234-803-456-7890',
                'address' => '78 Lekki-Epe Expressway, Ajah',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Ajah',
                'zipcode' => '101245',
                'latitude' => 6.4698,
                'longitude' => 3.5852,
                'logo_path' => 'logos/sunrise_health_facility.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Metro Medical Plaza',
                'hospital_type' => 'general',
                'reg_no' => 'usa/2026/01238',
                'lic_issue_dt' => '2023-11-12',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Michael Stevens',
                'ownership' => 'private',
                'beds' => 200,
                'email' => 'info@metroplaza.health',
                'contact_no' => '+1-555-234-5678',
                'address' => '5678 Broadway Avenue, New York, NY',
                'country' => 'USA',
                'state' => 'New York',
                'city' => 'New York',
                'zipcode' => '10001',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'logo_path' => 'logos/metro_medical_plaza.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Apollo Multispecialty Hospital',
                'hospital_type' => 'specialty',
                'reg_no' => 'in/2026/01244',
                'lic_issue_dt' => '2023-04-22',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Rajesh Kumar',
                'ownership' => 'private',
                'beds' => 250,
                'email' => 'info@apollomulti.in',
                'contact_no' => '+91-80-2345-6789',
                'address' => '154/11 Bannerghatta Road, Bangalore',
                'country' => 'India',
                'state' => 'Karnataka',
                'city' => 'Bangalore',
                'zipcode' => '560076',
                'latitude' => 12.9141,
                'longitude' => 77.6101,
                'logo_path' => 'logos/apollo_multispecialty_hospital.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Hope Children Hospital',
                'hospital_type' => 'pediatric',
                'reg_no' => 'ng/2026/01239',
                'lic_issue_dt' => '2023-02-28',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Fatima Bello',
                'ownership' => 'charitable',
                'beds' => 120,
                'email' => 'care@hopechildren.ng',
                'contact_no' => '+234-805-678-9012',
                'address' => '23 Ahmadu Bello Way, Abuja',
                'country' => 'Nigeria',
                'state' => 'FCT',
                'city' => 'Abuja',
                'zipcode' => '900001',
                'latitude' => 9.0579,
                'longitude' => 7.4951,
                'logo_path' => 'logos/hope_children_hospital.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'St. Mary Maternity Home',
                'hospital_type' => 'maternity',
                'reg_no' => 'ng/2026/01240',
                'lic_issue_dt' => '2024-05-18',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Grace Okafor',
                'ownership' => 'private',
                'beds' => 60,
                'email' => 'info@stmarymaternity.com',
                'contact_no' => '+234-807-890-1234',
                'address' => '56 Enugu Road, Port Harcourt',
                'country' => 'Nigeria',
                'state' => 'Rivers',
                'city' => 'Port Harcourt',
                'zipcode' => '500001',
                'latitude' => 4.8156,
                'longitude' => 7.0498,
                'logo_path' => 'logos/st_mary_maternity_home.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Elite Dental Care',
                'hospital_type' => 'dental',
                'reg_no' => 'usa/2026/01241',
                'lic_issue_dt' => '2024-09-30',
                'accred_status' => 'pending',
                'med_dir' => 'Dr. Robert Johnson',
                'ownership' => 'private',
                'beds' => 20,
                'email' => 'appointments@elitedental.us',
                'contact_no' => '+1-555-345-6789',
                'address' => '890 Dental Avenue, Miami, FL',
                'country' => 'USA',
                'state' => 'Florida',
                'city' => 'Miami',
                'zipcode' => '33101',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
                'logo_path' => 'logos/elite_dental_care.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Victory Rehabilitation Center',
                'hospital_type' => 'rehabilitation',
                'reg_no' => 'ng/2026/01242',
                'lic_issue_dt' => '2023-07-14',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Emmanuel Okeke',
                'ownership' => 'government',
                'beds' => 100,
                'email' => 'support@victoryrehab.gov.ng',
                'contact_no' => '+234-809-012-3456',
                'address' => '34 Independence Avenue, Ibadan',
                'country' => 'Nigeria',
                'state' => 'Oyo',
                'city' => 'Ibadan',
                'zipcode' => '200001',
                'latitude' => 7.3775,
                'longitude' => 3.9470,
                'logo_path' => 'logos/victory_rehabilitation_center.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'hospital_name' => 'Pacific Surgical Institute',
                'hospital_type' => 'surgical',
                'reg_no' => 'cn/2026/01243',
                'lic_issue_dt' => '2022-12-01',
                'accred_status' => 'accredited',
                'med_dir' => 'Dr. Li Wei',
                'ownership' => 'government',
                'beds' => 180,
                'email' => 'contact@pacificsurgical.cn',
                'contact_no' => '+86-10-6789-0123',
                'address' => '88 Dongcheng District, Beijing',
                'country' => 'China',
                'state' => 'Beijing',
                'city' => 'Beijing',
                'zipcode' => '100010',
                'latitude' => 39.9042,
                'longitude' => 116.4074,
                'logo_path' => 'logos/pacific_surgical_institute.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('hospitals')->insert($hospitals);
    }
}